---
title: "Estimating Relative Risk in Studies of Binary Outcomes Using the Doubling of Cases Approach"
author: "Yilin Ning"
output: 
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, collapse = TRUE)
```

Use the following code to install the package:

```{r, eval=FALSE}
# Package `devtools` required
devtools::install_github("nyilin/DoublingOfCases")
```

This package offers a function `logit_db` that estimates relative risk in
studies of binary outcomes by using the doubling-of-cases approach:

```{r}
library(DoublingOfCases)
data("cohort_sim")
# Draw a 1:1 case-control sample from cohort:
i_controls <- sample(which(cohort_sim$y == 0), size = sum(cohort_sim$y),
                     replace = FALSE)
dat_cc <- rbind(
  cbind(cohort_sim[cohort_sim$y == 1, ], w = 1),
  cbind(cohort_sim[i_controls, ], w = sum(cohort_sim$y == 0) / length(i_controls))
)
# Estimate relative risk (RR) by using doubling of cases approach:
# Fit the model:
m_cc <- logit_db(y ~ x + male, data = dat_cc, weight_name = "w")
# Extract model summary:
summ_cc <- summary(m_cc)
# Print the estimates log RR, RR, SEs and p-values:
summ_cc$coefficients
# Compute the 95% CI of the estimated RR:
confint(m_cc, exp = TRUE)
# Extract AIC, log-likelihood and fitted outcomes:
AIC(m_cc)
logLik(m_cc)
head(fitted(m_cc))
```
